development:
  title  : Joruri Plus+
  uri    : http://127.0.0.1/
  host   : 127.0.0.1
  proxy  :
  reminder : on
test:
  title  : Joruri Plus+
  uri    : http:///
  host   :
  proxy  :
  reminder :

production:
  title  : Joruri Plus+
  uri    : http:///
  host   :
  proxy  :
  reminder :
