development:
  adapter : mysql2
  database: joruri_plus
  username: joruri
  password: pass
  timeout : 5000
  encoding: utf8
  host: 127.0.0.1

test:
  adapter : 
  database: 
  username: 
  password: 
  timeout : 
  encoding: 
  host: 

production:
  adapter : 
  database: 
  username: 
  password: 
  timeout : 
  encoding: 
  host: 

jorurigw:
  adapter : 
  database: 
  username: 
  password: 
  timeout : 
  encoding: 
  host: 
